// <auto-generated />
using System;
using ApiProjectModul.AppDataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiProjectModul.Migrations
{
    [DbContext(typeof(AppDataBase))]
    [Migration("20200123121322_AllComposition")]
    partial class AllComposition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiProjectModul.Models.Composition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Compositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 1000,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 729, DateTimeKind.Local).AddTicks(4663),
                            Name = "Qanburger",
                            Type = "Starter"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 1100,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1416),
                            Name = "Hamburger",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 1200,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1465),
                            Name = "Spaghetti",
                            Type = "Dessert"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 1500,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1469),
                            Name = "Pizza",
                            Type = "Starter"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 2000,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1472),
                            Name = "Doner",
                            Type = "Doner"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 2500,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1475),
                            Name = "Sushi",
                            Type = "Sushi"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 3000,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1477),
                            Name = "Tonbalik",
                            Type = "Tonbalik"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 2000,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1480),
                            Name = "Qutab",
                            Type = "Qutab"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 2500,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1483),
                            Name = "Perashki",
                            Type = "Perashki"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 1500,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1485),
                            Name = "Corekarasi",
                            Type = "Corekarasi"
                        },
                        new
                        {
                            Id = 11,
                            Calories = 2500,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1488),
                            Name = "Qogal",
                            Type = "Qogal"
                        },
                        new
                        {
                            Id = 12,
                            Calories = 1000,
                            Created = new DateTime(2020, 1, 23, 16, 13, 21, 731, DateTimeKind.Local).AddTicks(1491),
                            Name = "Kasbmali",
                            Type = "Kasbmali"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
